version: "3"
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/data/database
    ports:
    - 38324:38324
    command: mongod --port 38324
  backend:
    build: .
    environment:
    - NODE_ENV=production
    ports:
    - 5000:5000
    links:
    - mongodb
    - redis
    volumes:
      - /etc/pki/tls/private/uniqcert.key:/usr/src/backend/uniqcert.key
      - /etc/pki/tls/uniqcert.fullchain:/usr/src/backend/uniqcert.fullchain
      - ../resumes:/usr/src/resumes
      - ${PWD}/stderr.log:/usr/src/backend/stderr.log
      - ${PWD}/stdout.log:/usr/src/backend/stdout.log