version: "3"
services:
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    user: postgres
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.c
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9999:80"
