version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    user: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - 5000:5000
    links:
      - postgres
    volumes:
      - ./data/resumes:/usr/src/backend/data/resumes
      - ./logs:/usr/src/backend/logs
      - ./backup:/usr/src/backend/backup
volumes:
  postgres-data:
