version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    user: postgres
    env_file:
      - .env
  postgres-test:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    user: postgres
    env_file:
      - .env
