version: "3"
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/data/database
    ports:
    - 127.0.0.1:38324:38324
    command: mongod --port 38324
    volumes:
      - ../data:/data/database
  backend:
    build: .
    environment:
    - NODE_ENV=production
    ports:
    - 5000:5000
    links:
    - mongodb
    - redis
    volumes:
      - ./server.key:/usr/src/backend/uniqcert.key
      - ./server.crt:/usr/src/backend/uniqcert.fullchain
      - ../resumes:/usr/src/resumes
      - ./stderr.log:/usr/src/backend/stderr.log
      - ./stdout.log:/usr/src/backend/stdout.log
