version: "3"
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo:latest
    ports:
    - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    command: "mongod --port ${DB_PORT}"
    volumes:
      - mongodb:/data/db
  backend:
    build: .
    env_file:
      - .env
    ports:
    - 5000:5000
    links:
    - mongodb
    - redis
    volumes:
      - ./server.key:/usr/src/backend/uniqcert.key
      - ./server.crt:/usr/src/backend/uniqcert.fullchain
      - ../resumes:/usr/src/resumes
      - ./stderr.log:/usr/src/backend/stderr.log
      - ./stdout.log:/usr/src/backend/stdout.log
volumes:
  mongodb:
